name: umap_visualization
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - holoviz
  - jupyterlab
  - numba=0.51.2
  - numpy=1.19.2
  - pandas=0.24.2
  - python=3.6
  - umap-learn=0.4.6
  - xarray=0.11.3
